/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function formatBrowserLog(logType: string, message: string): string | null

export declare function formatLogEntry(originalUrl: string, method: string, status: number, durationMs: number, contentLength?: number | undefined | null): string | null

export declare function getBrowserLoggerScript(): string
