/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function formatBrowserLog(logType: string, message: string, caller?: string | undefined | null, repeatCount?: number | undefined | null): string | null

export declare function formatLogEntry(originalUrl: string, method: string, status: number, durationMs: number, contentLength?: number | undefined | null, redirectLocation?: string | undefined | null, routeName?: string | undefined | null, repeatCount?: number | undefined | null): string | null

export declare function formatRouteLog(routeId: string, path: string, params?: string | undefined | null, durationMs?: number | undefined | null, isPreload?: boolean | undefined | null): string | null

export declare function getBrowserLoggerScript(): string
