/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function formatBrowserLog(logType: string, message: string, caller?: string | undefined | null, repeatCount?: number | undefined | null): string | null

export declare function formatGraphReevaluation(distinctModules: number, repeatedRequests: number, windowMs: number): string

export declare function formatLogEntry(originalUrl: string, method: string, status: number, durationMs: number, contentLength?: number | undefined | null, redirectLocation?: string | undefined | null, routeName?: string | undefined | null, repeatCount?: number | undefined | null): string | null

export declare function formatRouteLog(routeId: string, path: string, params?: string | undefined | null, durationMs?: number | undefined | null, isPreload?: boolean | undefined | null): string | null

export declare function getBrowserLoggerScript(): string

export declare function parseRouteTreeAst(content: string): Array<string>

export interface RemappedPosition {
  source?: string
  line: number
  column: number
  name?: string
}

export declare function remapSourcePosition(sourcemapJson: string, line: number, column: number): RemappedPosition | null

export declare function remapStackTrace(sourcemapJson: string, stack: string): string
