import type { Plugin } from 'vite'

// Import the native function generated by NAPI-RS
import { formatLogEntry, formatBrowserLog } from '../index.js'

export function requestLogger(): Plugin {
  return {
    name: 'vite-plugin-request-logging-rust',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const start = performance.now()

        let logged = false
        const logIt = () => {
          if (logged) return
          logged = true

          const durationMs = performance.now() - start
          const status = res.statusCode
          const contentLength = res.getHeader('content-length') as string | undefined

          // Call our blazing fast Rust function
          const logString = formatLogEntry(
            req.originalUrl || '',
            req.method || 'GET',
            status,
            durationMs,
            contentLength || null,
          )

          // If the Rust function returns a string (meaning it wasn't filtered out), print it
          if (logString) {
            console.log(logString)
          }
        }

        // Listen for both finish and close to catch aborted requests
        res.on('finish', logIt)
        res.on('close', logIt)

        next()
      })
    },
  }
}

export function browserLogger(): Plugin {
  const virtualModuleId = 'virtual:browser-logger'
  const resolvedVirtualModuleId = '\0' + virtualModuleId

  return {
    name: 'vite-plugin-browser-logger',
    enforce: 'pre',

    // Expose a virtual module to run the browser logging script
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId
      }
    },

    load(id) {
      if (id === resolvedVirtualModuleId) {
        return `
if (typeof window !== 'undefined' && import.meta.hot) {
  const originalLog = console.log;
  const originalError = console.error;
  const originalWarn = console.warn;
  const originalInfo = console.info;

  function safeStringify(obj) {
    const seen = new WeakSet();
    return JSON.stringify(obj, (key, value) => {
      if (typeof value === "object" && value !== null) {
        if (seen.has(value)) return "[Circular]";
        seen.add(value);
      }
      return value;
    }, 2);
  }

  function sendLog(type, args) {
    try {
      const message = Array.from(args).map(arg => {
        if (arg instanceof Error) {
          return arg.stack || arg.message;
        }
        if (typeof arg === 'object') {
          try { return safeStringify(arg); } catch(e) { return '[Object]'; }
        }
        return String(arg);
      }).join(' ');

      import.meta.hot.send('tameio:browser-log', { type, message });
    } catch(e) {}
  }

  // Only patch once
  if (!window.__BROWSER_LOGGER_PATCHED__) {
    window.__BROWSER_LOGGER_PATCHED__ = true;

    console.log = function(...args) {
      originalLog.apply(console, args);
      sendLog('log', args);
    };
    console.error = function(...args) {
      originalError.apply(console, args);
      sendLog('error', args);
    };
    console.warn = function(...args) {
      originalWarn.apply(console, args);
      sendLog('warn', args);
    };
    console.info = function(...args) {
      if (originalInfo) originalInfo.apply(console, args);
      sendLog('info', args);
    };

    window.addEventListener("error", (event) => {
      sendLog('error', ['[Uncaught Error]', event.error || event.message]);
    });

    window.addEventListener("unhandledrejection", (event) => {
      sendLog('error', ['[Unhandled Promise]', event.reason]);
    });
  }
}
`
      }
    },

    // Inject the virtual module into index.html so it runs unconditionally and early
    transformIndexHtml() {
      return [
        {
          tag: 'script',
          attrs: { type: 'module', src: '/@id/__x00__virtual:browser-logger' },
          injectTo: 'head-prepend',
        },
      ]
    },

    configureServer(server) {
      server.ws.on('tameio:browser-log', (data) => {
        const { type, message } = data

        const logString = formatBrowserLog(type, message)
        if (logString) {
          console.log(logString)
        }
      })
    },
  }
}
