import type { Plugin } from "vite";

// Import the native function generated by NAPI-RS
import { formatLogEntry, formatBrowserLog, getBrowserLoggerScript } from "../index.js";

export function requestLogger(): Plugin {
  return {
    name: "vite-plugin-request-logging-rust",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const start = performance.now();

        let logged = false;
        const logIt = () => {
          if (logged) return;
          logged = true;

          // Crucial memory leak optimization: remove listeners to release the closure
          res.removeListener("finish", logIt);
          res.removeListener("close", logIt);

          const durationMs = performance.now() - start;
          const status = res.statusCode;
          const cl = res.getHeader("content-length");
          const contentLength = cl ? Number(cl) : null;

          // Call our blazing fast Rust function
          const logString = formatLogEntry(
            req.originalUrl || "",
            req.method || "GET",
            status,
            durationMs,
            contentLength,
          );

          // If the Rust function returns a string (meaning it wasn't filtered out), print it
          if (logString) {
            console.log(logString);
          }
        };

        // Listen for both finish and close to catch aborted requests
        res.on("finish", logIt);
        res.on("close", logIt);

        next();
      });
    },
  };
}

export function browserLogger(): Plugin {
  const virtualModuleId = "virtual:browser-logger";
  const resolvedVirtualModuleId = "\0" + virtualModuleId;

  return {
    name: "vite-plugin-browser-logger",
    enforce: "pre",

    // Expose a virtual module to run the browser logging script
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },

    load(id) {
      if (id === resolvedVirtualModuleId) {
        return getBrowserLoggerScript();
      }
    },

    // Inject the virtual module into index.html so it runs unconditionally and early
    transformIndexHtml() {
      return [
        {
          tag: "script",
          attrs: { type: "module", src: "/@id/__x00__virtual:browser-logger" },
          injectTo: "head-prepend",
        },
      ];
    },

    configureServer(server) {
      server.ws.on("tameio:browser-log", (data) => {
        const { type, message } = data;

        const logString = formatBrowserLog(type, message);
        if (logString) {
          console.log(logString);
        }
      });
    },
  };
}
