import type { Plugin } from "vite";

// Import the native function generated by NAPI-RS
import { formatLogEntry, formatBrowserLog, formatRouteLog, getBrowserLoggerScript } from "../index.js";

export { remapSourcePosition, remapStackTrace, type RemappedPosition } from "../index.js";

export type ReqType =
  | "GET"
  | "POST"
  | "PUT"
  | "PATCH"
  | "DELETE"
  | "OPTIONS"
  | "HEAD"
  | "get"
  | "post"
  | "put"
  | "patch"
  | "delete"
  | "options"
  | "head"
  | "Get"
  | "Post"
  | "Put"
  | "Patch"
  | "Delete"
  | "Options"
  | "Head";

export interface RequestLoggerConfig {
  excludeReqType?: ReqType[];
  excludeUrls?: string[];
  resolveRoute?: (url: string) => string | undefined | null;
}

const DEFAULT_EXCLUDE_URLS = ["?import", "vite_ping", "@fs", "/@vite/client"];

export function requestLogger(config?: RequestLoggerConfig): Plugin {
  return {
    name: "vite-plugin-request-logging-rust",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = req.originalUrl || "";
        const method = req.method || "GET";

        if (
          config?.excludeReqType &&
          config.excludeReqType.some((type) => type.toLowerCase() === method.toLowerCase())
        ) {
          return next();
        }

        const exclusions = [...DEFAULT_EXCLUDE_URLS, ...(config?.excludeUrls || [])];
        if (exclusions.some((match) => url.includes(match))) {
          return next();
        }

        const start = performance.now();

        let logged = false;
        const logIt = () => {
          if (logged) return;
          logged = true;

          // Crucial memory leak optimization: remove listeners to release the closure
          res.removeListener("finish", logIt);
          res.removeListener("close", logIt);

          const durationMs = performance.now() - start;
          const status = res.statusCode;
          const cl = res.getHeader("content-length");
          const contentLength = cl ? Number(cl) : null;
          const location = res.getHeader("location");
          const redirectLocation = location ? String(location) : null;
          const routeName = config?.resolveRoute ? config.resolveRoute(url) : null;

          // Call our blazing fast Rust function
          const logString = formatLogEntry(
            req.originalUrl || "",
            req.method || "GET",
            status,
            durationMs,
            contentLength,
            redirectLocation,
            routeName,
            null,
          );

          // If the Rust function returns a string (meaning it wasn't filtered out), print it
          if (logString) {
            console.log(logString);
          }
        };

        // Listen for both finish and close to catch aborted requests
        res.on("finish", logIt);
        res.on("close", logIt);

        next();
      });
    },
  };
}

export function browserLogger(): Plugin {
  const virtualModuleId = "virtual:browser-logger";
  const resolvedVirtualModuleId = "\0" + virtualModuleId;

  return {
    name: "vite-plugin-browser-logger",
    enforce: "pre",

    // Expose a virtual module to run the browser logging script
    resolveId(id) {
      if (id === virtualModuleId) {
        return resolvedVirtualModuleId;
      }
    },

    load(id) {
      if (id === resolvedVirtualModuleId) {
        return getBrowserLoggerScript();
      }
    },

    // Inject the virtual module into index.html so it runs unconditionally and early
    transformIndexHtml() {
      return [
        {
          tag: "script",
          attrs: { type: "module", src: "/@id/__x00__virtual:browser-logger" },
          injectTo: "head-prepend",
        },
      ];
    },

    configureServer(server) {
      interface PendingBrowserLog {
        timer: ReturnType<typeof setTimeout>;
        count: number;
        type: string;
        message: string;
        caller: string | null;
      }

      const pendingBrowserLogs = new Map<string, PendingBrowserLog>();

      const flushBrowserLog = (key: string) => {
        const entry = pendingBrowserLogs.get(key);
        if (!entry) return;
        pendingBrowserLogs.delete(key);

        const logString = formatBrowserLog(
          entry.type,
          entry.message,
          entry.caller,
          entry.count > 1 ? entry.count : null,
        );
        if (logString) {
          console.log(logString);
        }
      };

      server.httpServer?.on("close", () => {
        for (const [key, entry] of pendingBrowserLogs.entries()) {
          clearTimeout(entry.timer);
          flushBrowserLog(key);
        }
      });

      const handleBrowserLog = (data: { type: string; message: string; caller?: string | null }) => {
        const { type, message, caller } = data;
        const callerStr = caller ?? null;
        const key = `${type}:${message}:${callerStr ?? ""}`;

        const existing = pendingBrowserLogs.get(key);
        if (existing) {
          existing.count += 1;
          clearTimeout(existing.timer);
          existing.timer = setTimeout(() => flushBrowserLog(key), 80);
          return;
        }

        const entry: PendingBrowserLog = {
          count: 1,
          type,
          message,
          caller: callerStr,
          timer: setTimeout(() => flushBrowserLog(key), 80),
        };
        pendingBrowserLogs.set(key, entry);
      };

      const handleTanStackRoute = (data: {
        routeId?: string;
        path: string;
        params?: string | null;
        durationMs?: number | null;
        isPreload?: boolean | null;
      }) => {
        const { routeId, path, params, durationMs, isPreload } = data;
        const logString = formatRouteLog(
          routeId || path,
          path,
          params ?? null,
          durationMs ? Number(durationMs) : null,
          Boolean(isPreload),
        );
        if (logString) {
          console.log(logString);
        }
      };

      server.ws.on("vite-plugin-logger:browser-log", handleBrowserLog);
      server.ws.on("vite-plugin-logger:tanstack-route", handleTanStackRoute);
    },
  };
}
