import type { Plugin } from "vite";

// Import the native function generated by NAPI-RS
import {
  formatLogEntry,
  formatBrowserLog,
  formatRouteLog,
  formatGraphReevaluation,
  getBrowserLoggerScript,
} from "../index.js";
import { GraphReevaluationDetector } from "./graph";

export { remapSourcePosition, remapStackTrace, type RemappedPosition } from "../index.js";

export type ReqType =
  | "GET"
  | "POST"
  | "PUT"
  | "PATCH"
  | "DELETE"
  | "OPTIONS"
  | "HEAD"
  | "get"
  | "post"
  | "put"
  | "patch"
  | "delete"
  | "options"
  | "head"
  | "Get"
  | "Post"
  | "Put"
  | "Patch"
  | "Delete"
  | "Options"
  | "Head";

export interface RequestLoggerConfig {
  excludeReqType?: ReqType[];
  excludeUrls?: string[];
  /**
   * Filter out Vite module compilation noise: both dependency modules
   * (`/node_modules/`, `/@vite`, `/@id/`) and your own source modules
   * (`/src/**`, `*.ts|tsx|js|jsx|css`). Set to `false` to log every module
   * request. Defaults to `true`.
   */
  excludeModules?: boolean;
  /**
   * Filter out `/api` endpoint requests from terminal logs.
   * Matches the `/api` path segment only, so `/api-key` is still logged.
   * @default false
   */
  excludeApis?: boolean;
  /**
   * Collapse repeated requests to the same URL within `repeatWindowMs` into a
   * single trailing `(xN)` line instead of printing one line each.
   * @default true
   */
  groupRepeats?: boolean;
  /**
   * Window used to group repeated requests.
   * @default 1000
   */
  repeatWindowMs?: number;
  /**
   * Print a diagnostic when many modules are requested a second time without an
   * intervening document request, which means the entry graph ran twice in one
   * page load.
   * @default true
   */
  detectGraphReevaluation?: boolean;
  resolveRoute?: (url: string) => string | undefined | null;
}

const DEFAULT_EXCLUDE_URLS = [
  "?import",
  "vite_ping",
  "@fs",
  "/@vite",
  "/@id/",
  "/@react-refresh",
  "/node_modules/",
  "/.well-known",
  "/__hyperlog",
];

const SOURCE_MODULE_RE = /\.(?:tsx|ts|jsx|js|mjs|cjs|css|vue|svelte)$/;

/** Maximum accepted body size for the SPA route reporting endpoint. */
const MAX_ROUTE_BODY_BYTES = 64 * 1024;

/**
 * Matches an exclusion pattern against a URL.
 *
 * Patterns starting with `/` are treated as path patterns and must align to
 * segment boundaries, so `/api` matches `/api/users` but not `/api-key` or
 * `/dashboard/apiSettings`. Everything else stays a substring match, which is
 * what query-shaped patterns like `?import` need.
 *
 * @internal exported for tests
 */
export function matchesExclusion(url: string, pattern: string): boolean {
  if (!pattern.startsWith("/")) {
    return url.includes(pattern);
  }

  const queryIndex = url.indexOf("?");
  const pathname = queryIndex === -1 ? url : url.slice(0, queryIndex);

  let from = 0;
  for (;;) {
    const idx = pathname.indexOf(pattern, from);
    if (idx === -1) return false;

    const before = idx === 0 ? undefined : pathname[idx - 1];
    const after = pathname[idx + pattern.length];
    const startsSegment = before === undefined || before === "/";
    // A pattern ending in "/" already consumes the separator, so there is no
    // trailing boundary left to check.
    const endsSegment = pattern.endsWith("/") || after === undefined || after === "/";
    if (startsSegment && endsSegment) return true;

    from = idx + 1;
  }
}

function toPathname(url: string): string {
  const queryIndex = url.indexOf("?");
  return queryIndex === -1 ? url : url.slice(0, queryIndex);
}

/**
 * True when the URL is a source or dependency module rather than an app request.
 *
 * @internal exported for tests
 */
export function isModuleRequest(url: string): boolean {
  if (url.startsWith("/api") || url.startsWith("/_serverFn")) return false;
  const pathname = toPathname(url);
  if (pathname.startsWith("/@")) return true;
  if (pathname.includes("/node_modules/")) return true;
  return SOURCE_MODULE_RE.test(pathname) || pathname.startsWith("/src/");
}

/**
 * Collects a request body as bytes.
 *
 * Concatenating chunks with `body += chunk` decodes each Buffer independently, so
 * a multi-byte character split across a chunk boundary is silently corrupted.
 * Buffering the raw bytes and decoding once at the end avoids that.
 */
function readBody(req: any, res: any, limit: number): Promise<Buffer | null> {
  return new Promise((resolve) => {
    const chunks: Buffer[] = [];
    let size = 0;
    let settled = false;

    const done = (value: Buffer | null) => {
      if (settled) return;
      settled = true;
      resolve(value);
    };

    req.on("data", (chunk: Buffer) => {
      size += chunk.length;
      if (size > limit) {
        if (!res.headersSent) {
          res.statusCode = 413;
          res.end();
        }
        req.destroy();
        done(null);
        return;
      }
      chunks.push(chunk);
    });

    req.on("end", () => done(Buffer.concat(chunks)));
    req.on("error", () => done(null));
    req.on("aborted", () => done(null));
  });
}

export interface RoutePayload {
  routeId?: string;
  path?: string;
  params?: string | null;
  durationMs?: number | null;
  isPreload?: boolean | null;
}

/** Logs one client-reported SPA route transition. */
export function logRouteEvent(data: RoutePayload): void {
  const logString = formatRouteLog(
    data.routeId || data.path || "",
    data.path || "",
    data.params ?? null,
    data.durationMs ? Number(data.durationMs) : null,
    Boolean(data.isPreload),
  );
  if (logString) console.log(logString);
}

/**
 * Attaches the SPA route reporting endpoint exactly once per dev server.
 *
 * `requestLogger`, `browserLogger`, and the TanStack adapter all want this route,
 * and registering it from more than one place produced copies that had already
 * started to drift (including the chunked-UTF-8 body bug). The WeakSet keeps the
 * first registration regardless of plugin order.
 */
const routeEndpointServers = new WeakSet<object>();

export function attachRouteEndpoint(server: any, onRoute: (data: RoutePayload) => void = logRouteEvent): void {
  if (routeEndpointServers.has(server)) return;
  routeEndpointServers.add(server);

  server.middlewares.use((req: any, res: any, next: () => void) => {
    if (req.url !== "/__hyperlog/route" || req.method !== "POST") {
      return next();
    }

    void readBody(req, res, MAX_ROUTE_BODY_BYTES).then((body) => {
      if (body) {
        try {
          onRoute(JSON.parse(body.toString("utf8")));
        } catch {
          // Malformed payloads are ignored rather than crashing the dev server.
        }
      }
      if (!res.writableEnded && !res.headersSent) {
        res.statusCode = body ? 204 : 400;
        res.end();
      }
    });
  });
}

export function requestLogger(config?: RequestLoggerConfig): Plugin {
  const excludeModules = config?.excludeModules ?? true;
  const groupRepeats = config?.groupRepeats ?? true;
  const repeatWindowMs = config?.repeatWindowMs ?? 1000;
  const detectGraphReevaluation = config?.detectGraphReevaluation ?? true;

  const exclusions = [
    ...DEFAULT_EXCLUDE_URLS,
    ...(config?.excludeUrls || []),
    ...(config?.excludeApis ? ["/api"] : []),
  ];
  const excludedMethods = config?.excludeReqType
    ? new Set(config.excludeReqType.map((type) => type.toUpperCase()))
    : null;
  const resolveRoute = config?.resolveRoute;

  return {
    name: "vite-plugin-request-logging-rust",
    apply: "serve",
    configureServer(server) {
      interface PendingRepeat {
        timer: ReturnType<typeof setTimeout>;
        count: number;
        totalDurationMs: number;
        status: number;
        method: string;
        url: string;
      }

      const repeats = new Map<string, PendingRepeat>();

      const flushRepeat = (key: string, entry: PendingRepeat) => {
        repeats.delete(key);
        if (entry.count <= 1) return;
        const summary = formatLogEntry(
          entry.url,
          entry.method,
          entry.status,
          entry.totalDurationMs,
          null,
          null,
          null,
          entry.count,
        );
        if (summary) console.log(summary);
      };

      server.httpServer?.on("close", () => {
        for (const [key, entry] of repeats) {
          clearTimeout(entry.timer);
          flushRepeat(key, entry);
        }
      });

      // --- Graph re-evaluation detection -------------------------------------
      // Observed before exclusions so it still sees module traffic that is not
      // logged, and reset by each document request to scope it to one page load.
      const detector = new GraphReevaluationDetector();

      const observe = (url: string) => {
        const report = detector.observe(isModuleRequest(url), url);
        if (report) {
          console.log(formatGraphReevaluation(report.distinctModules, report.repeatedRequests, report.windowMs));
        }
      };

      attachRouteEndpoint(server, logRouteEvent);

      server.middlewares.use((req, res, next) => {
        const url = req.originalUrl || "";
        const method = req.method || "GET";

        if (detectGraphReevaluation) {
          observe(url);
        }

        if (excludedMethods && excludedMethods.has(method.toUpperCase())) {
          return next();
        }

        for (let i = 0; i < exclusions.length; i++) {
          if (matchesExclusion(url, exclusions[i])) {
            return next();
          }
        }

        if (excludeModules && isModuleRequest(url)) {
          return next();
        }

        const start = performance.now();

        let logged = false;
        const logIt = (aborted: boolean) => {
          if (logged) return;
          logged = true;

          // Crucial memory leak optimization: remove listeners to release the closure
          res.removeListener("finish", onFinish);
          res.removeListener("close", onClose);

          const durationMs = performance.now() - start;
          // An aborted request never reaches `finish`, so statusCode is still the
          // default 200. Report 499 so a dropped request is not mistaken for a
          // successful one.
          const abortedRequest = aborted && !res.writableEnded;
          const status = abortedRequest ? 499 : res.statusCode;
          const cl = res.getHeader("content-length");
          const contentLength = cl ? Number(cl) : null;
          const location = res.getHeader("location");
          const redirectLocation = location ? String(location) : null;
          const routeName = resolveRoute ? resolveRoute(url) : null;

          if (!groupRepeats) {
            const line = formatLogEntry(
              url,
              method,
              status,
              durationMs,
              contentLength,
              redirectLocation,
              routeName,
              null,
            );
            if (line) console.log(line);
            return;
          }

          const key = `${method} ${url}`;
          const existing = repeats.get(key);
          if (existing) {
            existing.count += 1;
            existing.totalDurationMs += durationMs;
            existing.status = status;
            clearTimeout(existing.timer);
            existing.timer = setTimeout(() => flushRepeat(key, existing), repeatWindowMs);
            return;
          }

          const line = formatLogEntry(
            url,
            method,
            status,
            durationMs,
            contentLength,
            redirectLocation,
            routeName,
            null,
          );
          if (line) console.log(line);

          const entry: PendingRepeat = {
            // Armed immediately so a trailing repeat lands in this entry, then
            // rewritten on every subsequent repeat to extend the window.
            timer: setTimeout(() => {}, 0),
            count: 1,
            totalDurationMs: durationMs,
            status,
            method,
            url,
          };
          entry.timer = setTimeout(() => flushRepeat(key, entry), repeatWindowMs);
          repeats.set(key, entry);
        };

        const onFinish = () => logIt(false);
        const onClose = () => logIt(true);

        // Listen for both finish and close to catch aborted requests
        res.on("finish", onFinish);
        res.on("close", onClose);

        next();
      });
    },
  };
}

/**
 * Builds the dev URL for the browser logger virtual module.
 *
 * Vite serves virtual modules under `/@id/` with the leading NUL encoded as
 * `__x00__`, and prefixes that with the resolved `base`. Hardcoding the URL breaks
 * any app served from a sub-path.
 *
 * @internal exported for tests
 */
export function browserLoggerScriptSrc(base: string): string {
  const normalized = base.endsWith("/") ? base : `${base}/`;
  return `${normalized}@id/__x00__virtual:browser-logger`;
}

export function browserLogger(): Plugin {
  const virtualModuleId = "virtual:browser-logger";
  const resolvedVirtualModuleId = "\0" + virtualModuleId;

  // Defaults to "/" so the tag is still correct if configResolved has not run yet.
  let base = "/";

  return {
    name: "vite-plugin-browser-logger",
    // Dev-only. Without this the transformIndexHtml injection below also runs
    // during `vite build` and ships a dev-only virtual module URL to production.
    apply: "serve",
    enforce: "pre",

    configResolved(config) {
      base = config.base;
    },

    // Expose a virtual module to run the browser logging script
    resolveId(id) {
      if (id === virtualModuleId || id === resolvedVirtualModuleId || id.endsWith(virtualModuleId)) {
        return resolvedVirtualModuleId;
      }
    },

    load(id) {
      if (id === resolvedVirtualModuleId || id.endsWith(virtualModuleId)) {
        return getBrowserLoggerScript();
      }
    },

    // Inject the virtual module into index.html so it runs unconditionally and early
    transformIndexHtml() {
      return [
        {
          tag: "script",
          attrs: { type: "module", src: browserLoggerScriptSrc(base) },
          injectTo: "head-prepend",
        },
      ];
    },

    configureServer(server) {
      interface PendingBrowserLog {
        timer: ReturnType<typeof setTimeout>;
        count: number;
        type: string;
        message: string;
        caller: string | null;
      }

      const pendingBrowserLogs = new Map<string, PendingBrowserLog>();
      const MAX_PENDING_LOGS = 250;

      const flushBrowserLog = (key: string) => {
        const entry = pendingBrowserLogs.get(key);
        if (!entry) return;
        pendingBrowserLogs.delete(key);

        const logString = formatBrowserLog(
          entry.type,
          entry.message,
          entry.caller,
          entry.count > 1 ? entry.count : null,
        );
        if (logString) {
          console.log(logString);
        }
      };

      server.httpServer?.on("close", () => {
        for (const [key, entry] of pendingBrowserLogs.entries()) {
          clearTimeout(entry.timer);
          flushBrowserLog(key);
        }
      });

      const handleBrowserLog = (data: { type: string; message: string; caller?: string | null }) => {
        const { type, message, caller } = data;
        const callerStr = caller ?? null;
        const key = `${type}:${message}:${callerStr ?? ""}`;

        const existing = pendingBrowserLogs.get(key);
        if (existing) {
          existing.count += 1;
          // Prevent starvation: if logs repeat rapidly, flush at batch of 20
          if (existing.count >= 20) {
            clearTimeout(existing.timer);
            flushBrowserLog(key);
            return;
          }
          clearTimeout(existing.timer);
          existing.timer = setTimeout(() => flushBrowserLog(key), 80);
          return;
        }

        // Prevent unbounded memory growth if unique logs flood
        if (pendingBrowserLogs.size >= MAX_PENDING_LOGS) {
          const firstKey = pendingBrowserLogs.keys().next().value;
          if (firstKey) flushBrowserLog(firstKey);
        }

        const entry: PendingBrowserLog = {
          count: 1,
          type,
          message,
          caller: callerStr,
          timer: setTimeout(() => flushBrowserLog(key), 80),
        };
        pendingBrowserLogs.set(key, entry);
      };

      server.ws.on("vite-plugin-hyperlog:browser-log", handleBrowserLog);

      attachRouteEndpoint(server, logRouteEvent);
    },
  };
}

/**
 * Convenient unified plugin that registers both requestLogger and browserLogger in one call.
 *
 * @example
 * ```ts
 * import logger from "vite-plugin-hyperlog";
 * export default defineConfig({
 *   plugins: [logger()],
 * });
 * ```
 */
export function logger(config?: RequestLoggerConfig): Plugin[] {
  return [requestLogger(config), browserLogger()];
}

/**
 * Factory helper for framework-specific adapters (React, Solid, Svelte, Vue)
 * that injects default framework-specific exclusions while keeping behavior unified.
 */
export function createFrameworkLogger(defaultExclude: string) {
  function reqLogger(config?: RequestLoggerConfig): Plugin {
    return requestLogger({
      ...config,
      excludeUrls: [defaultExclude, ...(config?.excludeUrls || [])],
    });
  }
  function log(config?: RequestLoggerConfig): Plugin[] {
    return [reqLogger(config), browserLogger()];
  }
  return { requestLogger: reqLogger, logger: log };
}

export default logger;
